main: com.rayzr522.spawnergui.SpawnerGUI
name: SpawnerGUI
version: 1.0.1
description: A Bukkit plugin for purchasing randomized spawners
author: Rayzr
depend: [CreativelyNamedLib,SilkSpawners,Vault]
commands:
  spawners:
    description: SpawnerGUI main command
    aliases: [spawnergui]
    usage: /spawners [reload]
    permission: SpawnerGUI.open
