main: com.perceivedev.spawnergui.SpawnerGUI
name: SpawnerGUI
version: 1.0.0
description: A Bukkit plugin for purchasing randomized spawners
authors: [Perceive team]
depend: [PerceiveCore,Vault]
module:
  dependencies:
  - "Gui"
  - "Config"
commands:
  spawners:
    description: SpawnerGUI main command
    aliases: [spawnergui]
    usage: "\u00a7c Something has gone horribly wrong!"
    permission: SpawnerGUI.main
