main: com.rayzr522.spawnergui.SpawnerGUI
name: SpawnerGUI
version: 1.0.0
description: A Bukkit plugin for purchasing randomized spawners
author: Rayzr
depend: [CreativelyNamedLib,Vault]
commands:
  spawners:
    description: SpawnerGUI main command
    aliases: [spawnergui]
    usage: "\u00a7c Something has gone horribly wrong!"
    permission: SpawnerGUI.main
